

services:

  # Database to store XML data
  db-xml:
    container_name: db-xml
    build: images/db/xml
    volumes:
      - xml-data:/var/lib/postgresql/shared-data/
    ports:
      - "10001:5432"

  # Database to store Relational data
  db-rel:
    container_name: db-rel
    build: images/db/rel
    volumes:
      - rel-data:/var/lib/postgresql/shared-data/
    ports:
      - "10002:5432"

  # Container that automatically converts CSV to XML and then imports the XML to db-xml
  importer:
    container_name: importer
    build: images/python
    volumes:
      - ./src/daemon/importer:/usr/src/app
      - ./volumes/shared:/shared
      - ./volumes/csv:/csv
    environment:
      USE_DEV_MODE: ${USE_DEV_MODE}

  # Container that runs the RPC server
  rpc-server:
    container_name: rpc-server
    build: images/python
    volumes:
      - ./src/server/rpc:/usr/src/app
      - ./volumes/shared:/shared
    environment:
      USE_DEV_MODE: ${USE_DEV_MODE}
      RPC_SERVER_PORT: ${RPC_SERVER_PORT}

  # Container that runs the web interface for displaying entities
  frontend-ent:
    container_name: frontend-ent
    build: images/web
    volumes:
      - ./src/frontend/ent:/usr/src/app
      - ./volumes/shared:/shared
    ports:
      - "30001:30001"
    environment:
      USE_DEV_MODE: ${USE_DEV_MODE}
      WEB_PORT: 30001
      API_ENTITIES_URL: "api-entities:${API_PORT}"
      API_GIS_URL: "api-gis:${API_PORT}"
      API_GRAPHQL_URL: "api-entities:${API_PORT}"
      API_PROC_URL: "api-proc:${API_PORT}"

volumes:
  xml-data:
  rel-data:
